In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import seaborn as snb
from sklearn.model_selection import train_test_split,cross_val_score
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("Heart_Disease .csv")
data

,age,sex,cp,restbp,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,hd
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,132,0,1.2,2,0,7,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2,7,1
300,57,1,4,130,131,0,0,115,1,1.2,2,1,7,1
301,57,0,2,130,236,0,2,174,0,0.0,2,1,3,1
302,38,1,3,138,175,0,0,173,0,0.0,1,?,3,0

In [3]:
data.replace('?',np.nan,inplace=True)

data = data.astype(float)
data = data.apply(pd.to_numeric,errors='coerce')

data = data.dropna()
data = data.fillna(data.mean())

In [4]:
X = data.iloc[:,0:13]
Y = data.iloc[:,13]

In [5]:
data = pd.get_dummies(X,columns=['ca','thal','restecg','slope'])

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)
rfc = RandomForestClassifier(criterion='gini',random_state=42)
rfc.fit(X_train,Y_train)